@echo off
set PATH=C:\Program Files\nodejs;%PATH%
cd /d C:\Users\Lenovo\task-assistant
echo Starting Task Assistant...
echo Compiling Electron...
call npx tsc -p tsconfig.electron.json
echo Starting app...
start "" cmd /c "npx concurrently "npx vite" "wait-on http://localhost:5173 && npx electron .""
